/* Extra practice questions per chapter. Format: [question, correct, [3 wrong], explanation] */
(function () {
  const X = {
    essentials: [
      ['Which command prints the current working directory?', 'pwd', ['cwd', 'where', 'dir'], 'pwd = print working directory.'],
      ['What does ls -la show that plain ls does not?', 'Hidden files and long details (permissions, owner, size)', ['Only directories', 'Only executable files', 'File contents'], '-l gives the long format and -a includes dotfiles.'],
      ['Which directory mainly holds system-wide configuration files?', '/etc', ['/bin', '/tmp', '/proc'], '/etc stores configuration; /bin holds essential binaries.'],
      ['What does ~ expand to in the shell?', 'Your home directory', ['The root directory', 'The current directory', 'The parent directory'], 'The shell replaces ~ with $HOME.'],
      ['chmod 755 script.sh gives which permission string?', 'rwxr-xr-x', ['rwxrwxrwx', 'rw-r--r--', 'rwx------'], '7=rwx, 5=r-x, 5=r-x.'],
      ['Which command creates a symbolic link named lnk pointing to file?', 'ln -s file lnk', ['ln file lnk', 'link -s lnk file', 'cp -s file lnk'], 'ln -s TARGET LINKNAME makes a soft link.'],
      ['What does touch newfile do if newfile does not exist?', 'Creates an empty file', ['Prints an error', 'Creates a directory', 'Opens an editor'], 'touch creates an empty file (or updates timestamps of an existing one).'],
      ['Which command shows the manual page of ls?', 'man ls', ['help ls', 'info -m ls', 'doc ls'], 'man shows manual pages.'],
      ['wc -l notes.txt reports…', 'The number of lines', ['The number of words', 'The number of characters', 'The file size in KB'], '-l lines, -w words, -c bytes.'],
      ['Which command shows the first 3 lines of a file?', 'head -n 3 file', ['tail -n 3 file', 'top -3 file', 'cat -3 file'], 'head prints from the start, tail from the end.'],
    ],
    editors: [
      ['In vim normal mode, what does dd do?', 'Deletes (cuts) the current line', ['Duplicates the line', 'Deletes the whole file', 'Moves to the end'], 'dd cuts the line into the register so p can paste it.'],
      ['Which keys copy the current line and paste it below in vim?', 'yy then p', ['cc then p', 'dd then y', 'pp then yy'], 'yy yanks (copies) a line; p pastes after the cursor line.'],
      ['How do you quit vim without saving?', ':q!', [':wq', ':x', ':w'], ':q! quits and discards changes.'],
      ['In vim normal mode, which key undoes the last change?', 'u', ['r', 'z', 'U only'], 'u undoes; Ctrl+R redoes.'],
      ['Which command searches forward for "error" in vim?', '/error', ['?error', ':find error', '*error'], '/ searches forward, ? backward.'],
      ['What does :set number do in vim?', 'Shows line numbers', ['Counts words', 'Numbers the buffers', 'Sets the tab width'], 'It turns line numbering on.'],
      ['Which key sequence jumps to the first line of the file in vim?', 'gg', ['G', '0', '$'], 'gg = top, G = bottom.'],
      ['What is the difference between i and a in vim?', 'i inserts before the cursor, a after it', ['i is for files, a for lines', 'They are identical', 'a replaces text, i deletes'], 'Both enter insert mode at different positions.'],
      ['Which keys save and exit in nano?', 'Ctrl+O to write, then Ctrl+X to exit', ['Esc :wq', 'Ctrl+S then Ctrl+Q', 'Ctrl+Z'], 'nano shows its shortcuts at the bottom.'],
      ['Which vim key opens a new line below the current line and enters insert mode?', 'o', ['O', 'i', 'A'], 'o opens below; O opens above.'],
    ],
    network: [
      ['ping works using which protocol?', 'ICMP', ['TCP', 'SMTP', 'FTP'], 'ping sends ICMP echo requests.'],
      ['What does ssh-keygen create?', 'A public/private key pair', ['A password hash', 'An SSL certificate for web servers', 'A firewall rule'], 'You keep the private key and share the public one.'],
      ['Which permissions should a private SSH key have?', '600 (owner read/write only)', ['777', '644', '666'], 'ssh refuses keys that others can read.'],
      ['Which command copies a file to a remote host over SSH?', 'scp file user@host:/path', ['cp file user@host', 'ftp -s file host', 'ping file host'], 'scp = secure copy.'],
      ['The default port for HTTPS is…', '443', ['80', '22', '8080'], 'HTTP is 80, SSH is 22.'],
      ['What does DNS do?', 'Translates names to IP addresses', ['Encrypts traffic', 'Assigns IPs automatically', 'Blocks ports'], 'DNS resolves domain names.'],
      ['Which is the IPv4 loopback address?', '127.0.0.1', ['0.0.0.0', '192.168.0.1', '255.255.255.255'], 'localhost refers to your own machine.'],
      ['Which command shows the IP addresses of your interfaces on modern Linux?', 'ip addr', ['ifup', 'netcat -a', 'nslookup -i'], 'ip replaces the older ifconfig.'],
      ['curl -I https://example.com fetches…', 'Only the response headers', ['Only the body', 'Nothing, it pings', 'The SSL private key'], '-I sends a HEAD request.'],
      ['How many usable hosts are there in a /16 network?', '65534', ['65536', '254', '16384'], '2^16 − 2 (network and broadcast addresses).'],
    ],
    process: [
      ['What does ps aux show?', 'All processes of all users', ['Only your open files', 'Only background jobs', 'Only zombie processes'], 'a = all users, u = user format, x = without a terminal.'],
      ['Which signal does kill PID send by default?', 'SIGTERM (15)', ['SIGKILL (9)', 'SIGHUP (1)', 'SIGSTOP'], 'SIGTERM asks politely; SIGKILL cannot be caught.'],
      ['What does a trailing & do in cmd &?', 'Runs the command in the background', ['Runs it as root', 'Chains another command', 'Redirects errors'], 'The shell returns the prompt immediately.'],
      ['Which command lists the jobs of the current shell?', 'jobs', ['ps -j', 'top -j', 'bg -l'], 'jobs lists background and stopped jobs.'],
      ['Which signal is sent by Ctrl+C?', 'SIGINT', ['SIGTERM', 'SIGSTOP', 'SIGKILL'], 'Ctrl+C = interrupt, Ctrl+Z = stop (SIGTSTP).'],
      ['cmd1 || cmd2 runs cmd2 when…', 'cmd1 fails', ['cmd1 succeeds', 'always', 'cmd1 is stopped'], '|| is the "or" operator based on exit status.'],
      ['What does $$ contain?', 'The PID of the current shell', ['The PID of the last background job', 'The exit status', 'The number of arguments'], '$! is the last background PID; $? is the exit status.'],
      ['Which command lets a process survive after you log out?', 'nohup', ['nice', 'renice', 'fg'], 'nohup ignores the hangup signal.'],
      ['A lower nice value means…', 'Higher priority', ['Lower priority', 'More memory', 'Runs as root'], 'Nice ranges from −20 (highest priority) to 19.'],
      ['Which command kills processes by name?', 'pkill', ['killid', 'stopall', 'psdel'], 'pkill matches names, e.g. pkill firefox.'],
    ],
    software: [
      ['Which command installs a package and its dependencies?', 'sudo apt install pkg', ['dpkg -l pkg', 'apt show pkg', 'apt update pkg'], 'apt resolves dependencies automatically.'],
      ['What does apt upgrade do?', 'Upgrades installed packages to newer versions', ['Refreshes the package lists only', 'Removes old kernels', 'Installs a new OS'], 'update refreshes lists; upgrade installs newer versions.'],
      ['How does apt purge differ from apt remove?', 'purge also deletes configuration files', ['purge is faster', 'purge installs again', 'There is no difference'], 'remove keeps config files.'],
      ['Which command lists all installed packages?', 'dpkg -l', ['dpkg -i', 'apt search', 'apt edit-sources'], '-l lists; -i installs a .deb.'],
      ['What does apt autoremove do?', 'Removes dependencies no longer needed', ['Updates automatically', 'Removes every package', 'Cleans the shell history'], 'It cleans up orphaned dependencies.'],
      ['Which command lists the files installed by a package?', 'dpkg -L pkg', ['dpkg -S pkg', 'apt files pkg', 'dpkg -r pkg'], '-L lists files of a package; -S finds the owner of a file.'],
      ['Which command shows details (version, description) of a package?', 'apt show pkg', ['apt run pkg', 'dpkg -x pkg', 'apt look pkg'], 'apt show prints package metadata.'],
      ['Why do install commands usually need sudo?', 'They modify system directories', ['They need internet', 'They use the GPU', 'They run in the background'], 'Only root can write to system paths.'],
      ['Which package format does Debian/Ubuntu use?', '.deb', ['.rpm', '.exe', '.pkg'], '.rpm belongs to Red Hat-family systems.'],
      ['What does apt --fix-broken install try to do?', 'Repair missing or broken dependencies', ['Delete all caches', 'Downgrade the kernel', 'Restart the network'], 'It completes installs that stopped due to dependency problems.'],
    ],
    streams: [
      ['Which operator redirects only stderr to a file?', '2>', ['1>', '&>', '<'], 'File descriptor 2 is stderr.'],
      ['What does command > /dev/null do?', 'Discards stdout', ['Saves output in /dev', 'Appends output to a log', 'Runs the command twice'], '/dev/null throws away anything written to it.'],
      ['What does 2>&1 mean?', 'Send stderr to wherever stdout goes', ['Send stdout to stderr’s file only', 'Run two commands', 'Copy errors to the screen twice'], '&1 refers to the current destination of descriptor 1.'],
      ['Which is correct for sending both streams to a file?', 'cmd > f 2>&1', ['cmd 2>&1 > f', 'cmd > 2>&1 f', 'cmd 1>2 f'], 'Order matters: redirect stdout first, then point stderr at it.'],
      ['What does wc -l < file do?', 'Reads the file as stdin and prints the line count', ['Writes the count into file', 'Pipes file to wc', 'Appends file to itself'], '< redirects stdin from a file.'],
      ['What does tee -a do?', 'Appends to the file instead of overwriting', ['Adds all lines', 'Prints in an array', 'Truncates the file'], 'tee copies stdin to stdout and to files.'],
      ['What is a here-document?', 'Inline multi-line input given with <<MARK', ['A file stored in /here', 'A hidden file', 'A pipe to a remote host'], 'Input continues until the delimiter line.'],
      ['What does xargs do?', 'Builds command arguments from stdin', ['Extracts archives', 'Executes in a new terminal', 'Exports variables'], 'e.g. find . -name "*.tmp" | xargs rm.'],
      ['Which command sorts numbers correctly (10 after 9)?', 'sort -n', ['sort -r', 'sort -u', 'sort -k'], 'Without -n sorting is lexicographic.'],
      ['What does cmd > file do if file already exists?', 'Overwrites (truncates) it', ['Appends to it', 'Fails always', 'Makes a backup'], '>> appends.'],
    ],
    pattern: [
      ['In regex, what does . match?', 'Any single character', ['A literal dot only', 'Zero or more characters', 'The end of line'], 'Escape it as \\. for a literal dot.'],
      ['What does ^ mean at the start of a regex?', 'Anchors the match to the beginning of the line', ['Negation always', 'End of line', 'Any digit'], '$ anchors the end.'],
      ['What does [^abc] match?', 'Any one character except a, b or c', ['The text ^abc', 'a, b or c', 'Three characters'], '^ inside brackets negates the set.'],
      ['In ERE, what does colou?r match?', 'color and colour', ['colouur only', 'colr', 'colo?r literally'], '? means zero or one of the previous item.'],
      ['In ERE, what does a{2,4} match?', 'Two to four consecutive a’s', ['a or 2 or 4', 'exactly 24 a’s', 'a followed by 2,4'], '{m,n} is a range of repetitions.'],
      ['In a shell glob, what does ? match?', 'Exactly one character', ['Zero or one character', 'Any number of characters', 'A question mark only'], '* matches any number of characters.'],
      ['Which command converts lowercase to uppercase?', "tr 'a-z' 'A-Z'", ["tr -u a A", "cut -u", "sort -U"], 'tr translates characters from one set to another.'],
      ['What does cut -c1-3 print?', 'The first three characters of each line', ['Fields 1 to 3', 'The first three lines', 'Characters after position 3'], '-c selects character positions.'],
      ['What does | mean in ERE like cat|dog?', 'Alternation (either pattern)', ['Pipe to another command', 'Logical AND', 'Literal bar'], 'It matches cat or dog.'],
      ['Which command deletes every newline character?', "tr -d '\\n'", ["tr -s '\\n'", 'cut -d "\\n"', 'sort -z'], '-d deletes the listed characters.'],
    ],
    grep: [
      ['What does grep -i do?', 'Ignores case', ['Inverts the match', 'Includes line numbers', 'Searches recursively'], 'grep -i error matches Error and ERROR.'],
      ['Which option prints line numbers with matches?', '-n', ['-l', '-c', '-h'], '-n adds the line number.'],
      ['What does grep -c pattern file print?', 'The number of matching lines', ['The matches highlighted', 'The count of characters', 'Only filenames'], '-c counts lines, not individual matches.'],
      ['Which option lists only the names of files that contain a match?', '-l', ['-L', '-n', '-s'], '-L lists files without a match.'],
      ['Which option matches only whole words?', '-w', ['-x', '-o', '-e'], '-x requires the whole line to match.'],
      ['What does grep -A 2 pattern print?', 'Each match plus the 2 lines after it', ['2 matches only', 'The 2 lines before', 'All lines except 2'], '-B is before, -C is both sides.'],
      ['When is grep -F useful?', 'Searching a literal string without regex meaning', ['Faster file copying', 'Searching case-insensitively', 'Forcing recursion'], '-F treats the pattern as a fixed string.'],
      ['How do you search for two patterns with one grep?', 'grep -e one -e two file', ['grep one,two file', 'grep one&two file', 'grep -2 one two'], '-e can be repeated (or use -E "one|two").'],
      ['What does grep -x do?', 'Matches only if the entire line equals the pattern', ['Excludes a pattern', 'Extracts text', 'Searches hidden files'], 'x = exact line.'],
      ['What does grep -m 1 pattern file do?', 'Stops after the first matching line', ['Matches 1 character', 'Prints 1 line before', 'Merges one file'], '-m NUM stops reading after NUM matches.'],
    ],
    vars: [
      ['What does ${#name} give?', 'The length of the value of name', ['The name of the variable', 'The number of variables', 'The exit status'], 'For arrays ${#arr[@]} is the element count.'],
      ['What does $0 contain in a script?', 'The name of the script', ['The first argument', 'The number of arguments', 'The exit status'], '$1 is the first argument.'],
      ['What does $# give?', 'The number of positional arguments', ['The PID', 'The last argument', 'A comment'], 'Useful for checking whether enough arguments were given.'],
      ['echo \'$HOME\' prints…', '$HOME', ['/home/user', 'Nothing', 'An error'], 'Single quotes block all expansion.'],
      ['What does echo $((3+4*2)) print?', '11', ['14', '24', '9'], 'Multiplication happens before addition.'],
      ['With a=(x y z), echo ${a[1]} prints…', 'y', ['x', 'z', 'x y z'], 'Arrays are zero-indexed.'],
      ['With v=a.b.c, ${v#*.} gives…', 'b.c', ['a', 'c', 'a.b'], '# removes the shortest matching prefix.'],
      ['What does readonly PI=3 do?', 'Makes PI unchangeable', ['Exports PI', 'Hides PI', 'Deletes PI after reading'], 'Reassigning gives an error.'],
      ['What does $(date) do?', 'Command substitution: replaces it with the command output', ['Defines a variable named date', 'Starts a subshell and discards output', 'Prints the text date'], 'Same as backticks but nestable.'],
      ['With v=hello, ${v:1:3} gives…', 'ell', ['hel', 'ello', 'llo'], 'Syntax ${v:offset:length}, offset starts at 0.'],
    ],
    scripting: [
      ['What is the first line #!/bin/bash called?', 'A shebang', ['A comment block', 'An include line', 'A pragma'], 'It tells the kernel which interpreter runs the script.'],
      ['How do you make script.sh runnable as ./script.sh?', 'chmod +x script.sh', ['chmod -r script.sh', 'run script.sh', 'touch script.sh'], 'The executable bit is required.'],
      ['What does $1 refer to?', 'The first argument passed to the script', ['The exit status', 'The script name', 'The last argument'], '$0 is the script name.'],
      ['[ -d path ] is true when…', 'path is a directory', ['path is a file', 'path is empty', 'path is writable'], '-f tests for a regular file.'],
      ['Which test checks that a string is empty?', '[ -z "$s" ]', ['[ -n "$s" ]', '[ "$s" -eq 0 ]', '[ -e "$s" ]'], '-z true if length is zero; -n if non-zero.'],
      ['Which comparison is for numbers in [ ]?', '-eq', ['==', '=~', '-same'], 'Use -eq, -ne, -lt, -gt, -le, -ge for integers.'],
      ['What does shift do?', 'Drops $1 and moves the other arguments down', ['Shifts bits', 'Moves the script to the background', 'Rotates the output'], 'After shift, $2 becomes $1.'],
      ['What does set -u do?', 'Errors on use of unset variables', ['Unsets all variables', 'Updates variables', 'Disables errors'], 'It catches typos in variable names.'],
      ['What does break do inside a loop?', 'Exits the loop immediately', ['Skips to the next iteration', 'Stops the script', 'Pauses for input'], 'continue skips to the next iteration.'],
      ['What is trap used for?', 'Running a command when a signal or exit occurs', ['Catching syntax errors before running', 'Debugging variables', 'Blocking all input'], 'e.g. trap "rm -f tmp" EXIT.'],
    ],
    sed: [
      ['What does sed "s/a/b/g" do?', 'Replaces every a with b on each line', ['Replaces only the first a in the file', 'Deletes a', 'Prints a'], 'Without g only the first match per line changes.'],
      ['Which command prints only lines containing "x"?', 'sed -n "/x/p"', ['sed "/x/d"', 'sed "x/p"', 'sed -p "x"'], '-n turns off the default printing.'],
      ['What does sed "1d" do?', 'Deletes the first line', ['Deletes all lines except the first', 'Prints one line', 'Deletes the digit 1'], 'The address 1 selects line 1.'],
      ['Which command deletes the last line?', "sed '$d'", ["sed 'd$'", "sed '$p'", "sed -d last"], '$ is the address for the last line.'],
      ['What does sed "s/^/> /" do?', 'Adds "> " at the start of every line', ['Deletes the first character', 'Appends at the end', 'Replaces > with /'], '^ matches the start of the line.'],
      ['In a replacement, & stands for…', 'The whole matched text', ['An ampersand only', 'The line number', 'The previous command'], 's/cat/[&]/ turns cat into [cat].'],
      ['Which command deletes blank lines?', "sed '/^$/d'", ["sed '/$^/p'", "sed 's/ //'", "sed -b"], '^$ matches an empty line.'],
      ['What does sed "s/a/b/2" do?', 'Replaces the second a on each line', ['Replaces on line 2', 'Replaces a with b twice', 'Replaces a with b2'], 'A number flag picks the Nth occurrence.'],
      ['What does sed -n "2,4p" print?', 'Lines 2 through 4', ['Lines 2 and 4 only', 'All except 2–4', 'Four lines starting at 2'], 'It is an inclusive range.'],
      ['What does sed "2q" do?', 'Prints lines 1–2 then quits', ['Quits at the 2nd match', 'Quotes line 2', 'Deletes 2 lines'], 'q stops processing after printing the current line.'],
    ],
    awk: [
      ['In awk, what is $1?', 'The first field of the current record', ['The first line', 'The first character', 'The number 1'], '$0 is the whole line.'],
      ['What does NR hold?', 'The current record (line) number', ['The number of fields', 'The number of rows in the output', 'The file name'], 'NF is the number of fields.'],
      ['What does NF hold?', 'The number of fields in the current line', ['The number of files', 'The next field', 'The last record'], '$NF is the last field.'],
      ['Which block runs before any input is read?', 'BEGIN', ['START', 'INIT', 'PRE'], 'END runs after all input.'],
      ["Which sums column 1?", "awk '{s+=$1} END{print s}'", ["awk 'sum $1'", "awk '{print sum($1)}'", "awk '$1+=s'"], 'Accumulate in the main block, print in END.'],
      ["What does awk '$3>50' do?", 'Prints lines whose third field is greater than 50', ['Prints field 3 fifty times', 'Assigns 50 to $3', 'Prints the 50th line'], 'A condition with no action prints the line.'],
      ["What does awk '/err/' do?", 'Prints lines matching err', ['Counts errors', 'Deletes err', 'Prints the field err'], 'A regex pattern selects lines.'],
      ['Which variable sets the output field separator?', 'OFS', ['FS', 'ORS', 'RS'], 'FS is the input separator.'],
      ['What does length($0) return?', 'The number of characters in the line', ['The number of fields', 'The line number', 'The size of the file'], 'length with no argument also uses $0.'],
      ['What does for (k in arr) loop over?', 'The keys (indices) of the array', ['The values only', 'Characters of k', 'The lines of the file'], 'Use arr[k] to get the value.'],
    ],
    utils: [
      ['Which finds all .txt files below the current directory?', 'find . -name "*.txt"', ['grep .txt .', 'ls -R *.txt .', 'locate -r .'], 'find walks the directory tree.'],
      ['Which find option restricts results to directories?', '-type d', ['-dir', '-d only', '-folder'], '-type f is for files.'],
      ['Which command extracts a .tar.gz archive?', 'tar -xzf file.tar.gz', ['tar -czf file.tar.gz', 'gzip -x file', 'tar -tf file.tar.gz'], 'x extract, z gzip, f file; c would create.'],
      ['What does tar -tf archive.tar do?', 'Lists the archive contents', ['Tests the CPU', 'Extracts to /tmp', 'Compresses it'], 't = table of contents.'],
      ['How many time fields does a cron entry have before the command?', '5', ['3', '6', '7'], 'minute hour day-of-month month day-of-week.'],
      ['*/5 * * * * runs…', 'Every 5 minutes', ['Every 5 hours', 'At minute 5 only', 'Every 5 days'], '*/N in the minute field means every N minutes.'],
      ['Which command shows disk usage of a folder in human-readable form?', 'du -sh folder', ['df -h folder', 'ls -S folder', 'free -h'], 'du sums file usage; df shows filesystem free space.'],
      ['Which command compares two files line by line?', 'diff a b', ['cmp -l only', 'comm -x', 'sort a b'], 'diff shows the differences.'],
      ['What does find . -name "*.tmp" -exec rm {} \; do?', 'Deletes each found .tmp file', ['Lists them', 'Compresses them', 'Renames them'], '{} is replaced by each found path.'],
      ['Which prints today’s date like 2026-10-07?', 'date +%F', ['date -F', 'date --year', 'cal -d'], '%F is shorthand for %Y-%m-%d.'],
    ],
    extras: [
      ['What does git init do?', 'Creates a new empty repository', ['Downloads a repository', 'Commits all files', 'Deletes history'], 'It makes a .git directory.'],
      ['What does git commit record?', 'A snapshot of the staged changes', ['All untracked files', 'Only the file names', 'The remote URL'], 'Stage with git add first.'],
      ['Which command shows changed/staged/untracked files?', 'git status', ['git log', 'git diff --names', 'git show'], 'git log shows the commit history.'],
      ['Which command copies a remote repository to your machine?', 'git clone URL', ['git pull URL init', 'git fetch -all', 'git copy URL'], 'clone downloads the repo with its history.'],
      ['Which RAID level stripes data with no redundancy?', 'RAID 0', ['RAID 1', 'RAID 5', 'RAID 6'], 'RAID 0 is fast but any disk failure loses data.'],
      ['RAID 1 provides…', 'Mirroring', ['Striping only', 'Double parity', 'No redundancy'], 'Every write goes to two disks.'],
      ['RAID 5 can survive…', 'One disk failure', ['Two disk failures', 'No failures', 'All disks failing'], 'It uses distributed parity.'],
      ['Which command lists block devices (disks, partitions)?', 'lsblk', ['lsdisk -p', 'listfs', 'mountall'], 'lsblk shows a tree of disks and partitions.'],
      ['Which command shows memory usage in human-readable units?', 'free -h', ['df -h', 'du -m', 'mem -h'], 'free reports RAM and swap.'],
      ['Which variable defines the primary shell prompt?', 'PS1', ['PS2', 'PATH', 'PROMPT_CMD'], 'PS2 is the continuation prompt.'],
    ],
  };
  window.CH.forEach(c => {
    (X[c.id] || []).forEach(([q, right, wrong, e], i) => {
      const pos = (i * 3 + c.n) % 4, o = wrong.slice(); o.splice(pos, 0, right);
      c.quiz.push({ q, o, a: pos, e });
    });
  });
  /* Shell-script questions: [chapter, code, question, correct, [3 wrong], explanation, expectedStdout|undefined] */
  const S = [
    ['essentials', "touch a b c\nls | wc -l", 'Run in an empty directory, what does this script print?', '3', ['1', '0', '4'], 'touch creates three files; ls lists them one per line when piped; wc -l counts 3.', '3'],
    ['essentials', 'echo "hello" > f\necho "world" >> f\nwc -l < f', 'What does this print?', '2', ['1', '0', 'f 2'], '> creates/overwrites, >> appends, so f has two lines. Using < means wc prints no filename.', '2'],
    ['network', 'for h in 10.0.0.1 10.0.0.2; do\n  ping -c1 "$h" >/dev/null 2>&1 && echo "$h up" || echo "$h down"\ndone', 'If neither host answers, what does the script print?', '10.0.0.1 down, then 10.0.0.2 down', ['Nothing, output is sent to /dev/null', 'Both lines say up', 'An error and the loop stops'], 'ping returns non-zero on failure, so the || branch runs. The redirect hides only ping’s own output.'],
    ['process', 'false\necho $?', 'What does this print?', '1', ['0', 'false', 'Nothing'], '$? is the exit status of the last command; false exits with 1.', '1'],
    ['process', 'false && echo A || echo B', 'What does this print?', 'B', ['A', 'A then B', 'Nothing'], 'false fails so && skips echo A, then || runs echo B.', 'B'],
    ['process', '(exit 3)\necho $?', 'What does this print?', '3', ['0', '1', 'exit'], 'The subshell exits with status 3, which $? reports.', '3'],
    ['software', 'if dpkg -s curl >/dev/null 2>&1; then\n  echo "curl present"\nelse\n  sudo apt install -y curl\nfi', 'What does this script do?', 'Installs curl only if it is not already installed', ['Always reinstalls curl', 'Removes curl if present', 'Lists curl’s files'], 'dpkg -s returns success only when the package is installed.'],
    ['streams', 'echo hi | tee out.txt | tr a-z A-Z', 'What appears on the screen, and what is in out.txt?', 'Screen: HI, out.txt: hi', ['Screen: hi, out.txt: HI', 'Screen: HI, out.txt: HI', 'Nothing on screen'], 'tee saves the original text to the file and passes it on to tr.', 'HI'],
    ['streams', '{ echo err >&2; echo out; } 2>/dev/null', 'What does this print?', 'out', ['err', 'err and out', 'Nothing'], '2>/dev/null discards stderr, only stdout remains.', 'out'],
    ['streams', "printf 'b\\na\\nb\\n' | sort | uniq -c", 'What is the result?', '1 a, then 2 b', ['2 a, then 1 b', '3 b', '1 a, then 1 b'], 'sort groups equal lines; uniq -c counts each group.', '1 a 2 b'],
    ['pattern', 'echo "a1b22c333" | grep -oE \'[0-9]+\' | wc -l', 'What does this print?', '3', ['6', '1', '9'], '-o prints each digit run on its own line: 1, 22, 333.', '3'],
    ['pattern', 'echo "a,b,c" | cut -d, -f2,3', 'What does this print?', 'b,c', ['a,b', 'b c', 'c'], '-f2,3 keeps fields 2 and 3 joined by the delimiter.', 'b,c'],
    ['grep', "printf 'apple\\nBanana\\ncherry\\n' | grep -ci an", 'What does this print?', '1', ['0', '2', '3'], '-i ignores case and -c counts matching lines; only Banana contains "an".', '1'],
    ['grep', "printf 'cat\\ncatalog\\nbobcat\\n' | grep -w cat", 'Which lines are printed?', 'cat', ['cat and catalog', 'cat and bobcat', 'All three'], '-w requires "cat" to be a whole word.', 'cat'],
    ['grep', "printf 'a\\nb\\nc\\n' | grep -v b | wc -l", 'What does this print?', '2', ['1', '3', '0'], '-v inverts the match leaving a and c.', '2'],
    ['vars', 'x=5\ny=$((x*2))\necho "$x$y"', 'What does this print?', '510', ['15', '55', '10'], '"$x$y" concatenates 5 and 10.', '510'],
    ['vars', 'name=World\necho "Hello ${name:-Guest} ${missing:-Guest}"', 'What does this print?', 'Hello World Guest', ['Hello Guest Guest', 'Hello World World', 'Hello World'], '${var:-default} uses default only when var is unset or empty.', 'Hello World Guest'],
    ['vars', 'f=archive.tar.gz\necho ${f%.gz} ${f##*.}', 'What does this print?', 'archive.tar gz', ['archive tar.gz', 'archive.tar archive', 'archive.tar.gz gz'], '% removes the shortest suffix; ##*. removes the longest prefix ending in a dot.', 'archive.tar gz'],
    ['vars', 'set -- a b c\necho $# $2', 'What does this print?', '3 b', ['3 a', '2 b', 'c 3'], 'set -- assigns positional parameters.', '3 b'],
    ['vars', 'a=(10 20 30)\necho ${#a[@]} ${a[-1]}', 'What does this print?', '3 30', ['3 10', '2 30', '30 3'], '${#a[@]} is the number of elements; index -1 is the last one.', '3 30'],
    ['scripting', 'for i in 1 2 3; do\n  [ $i -eq 2 ] && continue\n  echo -n $i\ndone', 'What does this print?', '13', ['123', '12', '23'], 'continue skips the echo when i is 2.', '13'],
    ['scripting', 'n=3\nwhile [ $n -gt 0 ]; do\n  echo -n $n\n  n=$((n-1))\ndone', 'What does this print?', '321', ['123', '210', '3'], 'The loop counts down while n > 0.', '321'],
    ['scripting', 'f() { return 4; }\nf\necho $?', 'What does this print?', '4', ['0', 'f', '1'], 'return sets the function’s exit status, read via $?.', '4'],
    ['scripting', 'case "b" in\n  a) echo A;;\n  b|c) echo BC;;\n  *) echo other;;\nesac', 'What does this print?', 'BC', ['A', 'other', 'Nothing'], 'The pattern b|c matches "b".', 'BC'],
    ['scripting', 's=""\n[ -z "$s" ] && echo empty || echo full', 'What does this print?', 'empty', ['full', 'Nothing', 'An error'], '-z is true for an empty string.', 'empty'],
    ['scripting', 'set -e\nfalse\necho after', 'What does this print?', 'Nothing, the script stops at false', ['after', 'false', 'An error message and then after'], 'set -e exits on the first failing command.', ''],
    ['scripting', 'echo "a b" | read p q\necho "[$p]"', 'In bash, what does this print?', '[]', ['[a]', '[a b]', '[b]'], 'Each pipeline stage runs in a subshell, so p is not set in the parent shell.', '[]'],
    ['sed', "printf 'one\\ntwo\\nthree\\n' | sed -n '2p'", 'What does this print?', 'two', ['one', 'three', 'one two three'], '-n with p prints only line 2.', 'two'],
    ['sed', 'echo "hello world" | sed \'s/o/0/g\'', 'What does this print?', 'hell0 w0rld', ['hell0 world', 'hello w0rld', 'hello world'], 'g replaces every o on the line.', 'hell0 w0rld'],
    ['sed', "printf 'a\\nb\\nc\\n' | sed '2d'", 'What does this print?', 'a, then c', ['b', 'a, b', 'a only'], 'The d command deletes line 2.', 'a c'],
    ['sed', 'echo "2026-10-07" | sed -E \'s/([0-9]+)-([0-9]+)-([0-9]+)/\\3\\/\\2\\/\\1/\'', 'What does this print?', '07/10/2026', ['2026/10/07', '10/07/2026', '07-10-2026'], 'Groups 1,2,3 are year, month, day; the replacement reverses their order.', '07/10/2026'],
    ['awk', "printf '1 2\\n3 4\\n' | awk '{s+=$2} END{print s}'", 'What does this print?', '6', ['4', '10', '3'], 'It sums the second column: 2 + 4.', '6'],
    ['awk', "printf 'a b c\\nd e\\n' | awk '{print NF}'", 'What does this print?', '3, then 2', ['2, then 3', '5', '1, then 1'], 'NF is the number of fields on each line.', '3 2'],
    ['awk', 'echo "x:y:z" | awk -F: \'{print $2, $NF}\'', 'What does this print?', 'y z', ['x z', 'y y', 'x:y z'], '-F: sets the separator, $NF is the last field.', 'y z'],
    ['awk', "printf 'a\\nb\\na\\n' | awk '!s[$0]++'", 'What does this print?', 'a, then b', ['a, b, a', 'b only', 'a only'], 'It prints a line only the first time it is seen.', 'a b'],
    ['awk', "printf '5\\n15\\n25\\n' | awk '$1>10{c++} END{print c}'", 'What does this print?', '2', ['3', '1', '25'], 'Two values are greater than 10.', '2'],
    ['utils', "mkdir d\ntouch d/a.txt d/b.log\nfind d -name '*.txt'", 'What does this print?', 'd/a.txt', ['d/b.log', 'd/a.txt and d/b.log', 'Nothing'], 'find filters by name pattern.', 'd/a.txt'],
    ['utils', "printf '3\\n1\\n2\\n' | sort -n | tail -1", 'What does this print?', '3', ['1', '2', '123'], 'sorted numerically, the last line is the largest.', '3'],
    ['utils', "echo 'a b c' | xargs -n1", 'What does this print?', 'a, b and c on separate lines', ['a b c on one line', 'Nothing', 'An error'], '-n1 passes one argument per echo call.', 'a b c'],
    ['extras', 'git init demo\ncd demo\necho hi > f.txt\ngit add f.txt\ngit commit -m "first"', 'What state is the repository in after these commands?', 'One commit containing f.txt', ['Nothing is saved yet', 'f.txt is untracked', 'The commit failed because there is no remote'], 'Commits are local; a remote is only needed for push.'],
  ];
  S.forEach(([id, code, q, right, wrong, e, chk], i) => {
    const c = window.CH.find(x => x.id === id); if (!c) return;
    const pos = (i * 3 + 1) % 4, o = wrong.slice(); o.splice(pos, 0, right);
    c.quiz.push({ q, code, o, a: pos, e, chk });
  });
})();
